version: "3.9"

services:
  backend:
    platform: linux/arm64/v8
    build:
      context: fastapi_backend
    env_file:
      - ./fastapi_backend/.env
    environment:
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/mydatabase
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:password@db_test:5432/testdatabase
      MAIL_SERVER: mailhog
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - ./fastapi_backend:/app
      - fastapi-venv:/app/.venv
      - ./local-shared-data:/app/shared-data
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

#  db_test:
#    image: postgres:17
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: testdatabase
#    ports:
#      - "5433:5432"
#    networks:
#      - my_network
#    restart: always
#    volumes:
#      - test_postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./nextjs-frontend
    user: root # todo: want to de-escalate privileges to user: node
    environment:
      NODE_ENV: production
      API_BASE_URL: http://backend:8000
      NEXT_PUBLIC_API_BASE_URL: http://edupulse.net:8000
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - ./nextjs-frontend:/app
      - nextjs-node-modules:/app/node_modules
      - ./local-shared-data:/app/shared-data

#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - "1025:1025"
#      - "8025:8025"
#    networks:
#      - my_network

volumes:
  postgres_data:
  test_postgres_data:
  nextjs-node-modules:
  fastapi-venv:

networks:
  my_network:
    driver: bridge